
name: Tests

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        python-version: [3.8, "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install nox_poetry
    - name: Test with nox
      env:
        NEXTCLOUD_FOLDER_URI: ${{ secrets.NEXTCLOUD_FOLDER_URI }}
        NEXTCLOUD_FOLDER_PW: ${{ secrets.NEXTCLOUD_FOLDER_PW }}
      run: nox -s tests

